Repository sonata-project/SonataTranslationBundle, pull requests merged in 2018-02, with the labels that each got.

#224 Minor composer improvement
  composer.json
Labels: pedantic

#226 Add style for locale switcher in modal
  src/Resources/public/css/sonata-translation.css
Labels: patch

#225 Improve docs for importing css
  docs/reference/installation.rst
Labels: docs
