Repository sonata-project/SonataTranslationBundle, pull requests merged in 2020-10, with the labels that each got.

#384 Add PHPStan check
  .github/workflows/qa.yaml
  composer.json
  phpstan.neon.dist
  src/Admin/Extension/AbstractTranslatableAdminExtension.php
Labels: pedantic

#383 Allow to install latest version of sonata packages
  composer.json
  src/Admin/Extension/AbstractTranslatableAdminExtension.php
  src/Filter/TranslationFieldFilter.php
Labels: major

#391 Mark classes as final
  src/Admin/Extension/Gedmo/TranslatableAdminExtension.php
  src/Admin/Extension/Knplabs/TranslatableAdminExtension.php
  src/Admin/Extension/Phpcr/TranslatableAdminExtension.php
  src/Block/LocaleSwitcherBlockService.php
  src/Checker/TranslatableChecker.php
  src/DependencyInjection/Compiler/AdminExtensionCompilerPass.php
  src/DependencyInjection/Compiler/GlobalVariablesCompilerPass.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataTranslationExtension.php
  src/EventListener/LocaleSwitcherListener.php
  src/SonataTranslationBundle.php
  src/Twig/Extension/SonataTranslationExtension.php
Labels: minor

#394 Add psalm
  .github/workflows/qa.yaml
  composer.json
  phpstan-baseline.neon
  phpstan.neon.dist
  psalm-baseline.xml
  psalm.xml
  src/Filter/TranslationFieldFilter.php
Labels: pedantic

#405 Add pt language
  src/Resources/translations/SonataTranslationBundle.pt.xliff
Labels: minor
