Repository sonata-project/SonataTranslationBundle, pull requests merged in 2021-12, with the labels that each got.

#585 Resolve next major comments
  psalm.xml
  src/Admin/Extension/Gedmo/TranslatableAdminExtension.php
  src/DependencyInjection/SonataTranslationExtension.php
  src/Model/Gedmo/TranslatableInterface.php
  src/Model/TranslatableInterface.php
  tests/Admin/Extension/AbstractTranslatableAdminExtensionTest.php
  tests/Admin/Extension/Gedmo/TranslatableAdminExtensionTest.php
Labels: pedantic

#596 Update doc
  docs/reference/custom_action.rst
  docs/reference/orm.rst
Labels: docs

#597 Move framework bundle to require section
  composer.json
Labels: pedantic

#599 Remove UserLocaleSubscriber
  UPGRADE-3.0.md
  src/EventSubscriber/UserLocaleSubscriber.php
  src/Resources/config/service_locale_switcher.php
  tests/EventSubscriber/LocalizedUser.php
  tests/EventSubscriber/User.php
  tests/EventSubscriber/UserLocaleSubscriberTest.php
Labels: major

#598 Only call refresh when the locale is different in the entity
  src/Admin/Extension/Gedmo/TranslatableAdminExtension.php
  tests/Admin/Extension/Gedmo/TranslatableAdminExtensionTest.php
  tests/Fixtures/Model/ModelTranslatable.php
Labels: patch

#606 Manual merge
  src/Admin/Extension/Gedmo/TranslatableAdminExtension.php
  tests/Admin/Extension/Gedmo/TranslatableAdminExtensionTest.php
  tests/Fixtures/Model/ModelTranslatable.php
Labels: pedantic

#609 Manual merge
  CHANGELOG.md
Labels: pedantic
