Repository sonata-project/SonataTranslationBundle, pull requests merged in 2021-11, with the labels that each got.

#559 Remove TranslatableInterface::getLocale
  src/Admin/Extension/Gedmo/TranslatableAdminExtension.php
  src/Model/TranslatableInterface.php
  tests/App/Entity/GedmoCategory.php
  tests/Fixtures/Model/ModelTranslatable.php
Labels: major

#573 Manual merge
  .github/workflows/test.yaml
Labels: pedantic

#576 Improve PHPStan and Psalm
  composer.json
  phpstan.neon.dist
  psalm.xml
  tests/Fixtures/Model/Knplabs/TranslatableEntity.php
  tests/Fixtures/Traits/ORM/ArticlePersonalTranslatable.php
  tests/Fixtures/Traits/ORM/ArticlePersonalTranslation.php
  tests/Fixtures/Traits/ORM/Knplabs/Article.php
Labels: pedantic

#578 Allow to install symfony/* 5.x dependencies
  composer.json
  src/Provider/RequestLocaleProvider.php
Labels: minor

#571 Deprecate model interfaces
  UPGRADE-2.x.md
  src/Admin/Extension/Gedmo/TranslatableAdminExtension.php
  src/DependencyInjection/SonataTranslationExtension.php
  src/Filter/TranslationFieldFilter.php
  src/Model/Gedmo/TranslatableInterface.php
  src/Model/TranslatableInterface.php
  tests/Admin/Extension/Gedmo/DeprecatedTranslatableAdminExtensionTest.php
  tests/Admin/Extension/Gedmo/TranslatableAdminExtensionTest.php
  tests/App/Entity/GedmoCategory.php
  tests/App/config/services.php
  tests/Checker/TranslatableCheckerTest.php
  tests/Fixtures/Model/DeprecatedModelTranslatable.php
  tests/Fixtures/Model/ModelTranslatable.php
  tests/Model/GedmoTest.php
Labels: minor

#558 Drop support for PHP 7.3
  composer.json
  src/Admin/Extension/AbstractTranslatableAdminExtension.php
  src/Admin/Extension/Gedmo/TranslatableAdminExtension.php
  src/Block/LocaleSwitcherBlockService.php
  src/Checker/TranslatableChecker.php
  src/EventSubscriber/LocaleSubscriber.php
  src/Filter/TranslationFieldFilter.php
  src/Provider/Knplabs/LocaleProvider.php
  src/Provider/RequestLocaleProvider.php
  src/Twig/Extension/SonataTranslationExtension.php
  tests/Admin/Extension/AbstractTranslatableAdminExtensionTest.php
  tests/Admin/Extension/Gedmo/TranslatableAdminExtensionTest.php
  tests/Admin/Extension/Knplabs/TranslatableAdminExtensionTest.php
  tests/App/Entity/GedmoCategory.php
  tests/App/Entity/KnpCategory.php
  tests/App/Entity/KnpCategoryTranslation.php
  tests/EventSubscriber/LocalizedUser.php
  tests/Fixtures/Model/Knplabs/TranslatableEntity.php
  tests/Fixtures/Model/Knplabs/TranslatableEntityTranslation.php
  tests/Fixtures/Model/ModelTranslatable.php
  tests/Fixtures/Traits/ORM/ArticlePersonalTranslatable.php
  tests/Fixtures/Traits/ORM/Knplabs/AbstractArticleTranslation.php
  tests/Fixtures/Traits/ORM/Knplabs/Article.php
  tests/Functional/GedmoCRUDTest.php
  tests/Functional/KnpCRUDTest.php
  tests/Provider/Knplabs/LocaleProviderTest.php
  tests/Resources/XliffTest.php
  tests/Traits/DoctrineOrmTestCase.php
  tests/Traits/GedmoOrmTest.php
  tests/Traits/KnplabsOrmTest.php
Labels: major
