Repository sonata-project/SonataTranslationBundle, pull requests merged in 2021-09, with the labels that each got.

#531 Add functional tests for Gedmo
  composer.json
  tests/App/Admin/GedmoCategoryAdmin.php
  tests/App/AppKernel.php
  tests/App/DataFixtures/GedmoCategoryFixtures.php
  tests/App/Entity/GedmoCategory.php
  tests/App/config/config_v4.yml
  tests/App/config/config_v5.yml
  tests/App/config/routes.yaml
  tests/App/config/security_v4.yml
  tests/App/config/security_v5.yml
  tests/App/config/services.php
  tests/Checker/TranslatableCheckerForKnpTest.php
  tests/Functional/GedmoCRUDTest.php
  tests/custom_bootstrap.php
Labels: pedantic

#535 Manual merge
  .php-cs-fixer.dist.php
  tests/Action/SwitchLocaleActionTest.php
  tests/Admin/Extension/AbstractTranslatableAdminExtensionTest.php
  tests/Admin/Extension/Gedmo/TranslatableAdminExtensionTest.php
  tests/Admin/Extension/Knplabs/TranslatableAdminExtensionTest.php
  tests/Checker/TranslatableCheckerForKnpTest.php
  tests/Checker/TranslatableCheckerTest.php
  tests/EventSubscriber/LocaleSubscriberTest.php
  tests/EventSubscriber/UserLocaleSubscriberTest.php
  tests/Model/GedmoTest.php
  tests/Model/KnplabsTest.php
  tests/Resources/XliffTest.php
  tests/Traits/GedmoOrmTest.php
  tests/Traits/GedmoTest.php
  tests/Traits/KnplabsOrmTest.php
Labels: pedantic

#537 Deprecate abstract classes and traits for translatable models
  UPGRADE-2.x.md
  src/Checker/TranslatableChecker.php
  src/Model/AbstractTranslatable.php
  src/Model/Gedmo/AbstractPersonalTranslatable.php
  src/Model/Gedmo/AbstractPersonalTranslation.php
  src/Model/Gedmo/AbstractTranslatable.php
  src/Traits/Gedmo/PersonalTranslatableTrait.php
  src/Traits/Gedmo/TranslatableTrait.php
  src/Traits/TranslatableTrait.php
  tests/Checker/TranslatableCheckerTest.php
  tests/Fixtures/Model/ModelUsingTraitTranslatable.php
Labels: minor

#541 Remove references to abstract classes and traits in docs
  docs/reference/orm.rst
Labels: docs

#523 Remove flag related css
  src/Resources/public/css/sonata-translation.css
  src/Resources/public/less/sonata-translation.less
Labels: pedantic

#555 Update homepage
  composer.json
Labels: pedantic
