Repository sonata-project/SonataTranslationBundle, pull requests merged in 2021-08, with the labels that each got.

#524 Add strict rules
  composer.json
  tests/Action/SwitchLocaleActionTest.php
  tests/Admin/Extension/AbstractTranslatableAdminExtensionTest.php
  tests/Admin/Extension/Gedmo/TranslatableAdminExtensionTest.php
  tests/Admin/Extension/Knplabs/TranslatableAdminExtensionTest.php
  tests/Checker/TranslatableCheckerForKnpTest.php
  tests/Checker/TranslatableCheckerTest.php
  tests/EventSubscriber/LocaleSubscriberTest.php
  tests/EventSubscriber/UserLocaleSubscriberTest.php
  tests/Model/GedmoTest.php
  tests/Model/KnplabsTest.php
  tests/Resources/XliffTest.php
  tests/Traits/DoctrineOrmTestCase.php
  tests/Traits/GedmoOrmTest.php
  tests/Traits/GedmoTest.php
  tests/Traits/KnplabsOrmTest.php
Labels: pedantic

#525 Bump to symfony 5.3 and use rc versions of sonata
  composer.json
Labels: major

#526 Update doc url
  docs/reference/global_locale_switcher.rst
  docs/reference/installation.rst
Labels: docs
