Repository sonata-project/SonataTranslationBundle, pull requests merged in 2023-06, with the labels that each got.

#692 DevKit updates for 3.x branch
  .php-cs-fixer.dist.php
  src/DependencyInjection/Compiler/AdminExtensionCompilerPass.php
  tests/Fixtures/Traits/ORM/Knplabs/AbstractArticleTranslation.php
  tests/Resources/XliffTest.php
Labels: automerge, dev-kit

#693 Add support for BlockBundle 5.0
  .github/workflows/test.yaml
  composer.json
Labels: minor

#694 Release 3.3.0
  CHANGELOG.md
Labels: dev-kit

#695 Cleanup older upgrade files
  UPGRADE-2.x.md
  UPGRADE-3.x.md
Labels: pedantic

#697 Update rector
  composer.json
Labels: pedantic
